### ISSUE TITLE
Create list of components

### ISSUE THREAD

**Issue by arisgk** [universelabs/meta#16]
Gather feedback from the community for component requests. Needs identified until now:
- Public Key (proposed by @guylepage3)

**Comment by JWhiteUX** [comment]
Are there components you need designed, or need specs for? Happy to contribute UI specs if needed.

**Comment by guylepage3** [comment]
Hey @JWhiteUX yes there are.. I think designing the Public Key component is the first one on the block.

**Comment by guylepage3** [comment]
I'll be working on a new "Public key" component this weekend. :)

**Comment by guylepage3** [comment]
Closing issue. If folks want to request a feature they can do so via the Request a Feature issue creator.
