### ISSUE TITLE
Create a UI Explorer (e.g. React Storybook)

### ISSUE THREAD

**Issue by JWhiteUX** [universelabs/meta#27]
**Is your feature request related to a problem? Please describe.**
there is currently no easy/web-based way to explore the UI components and it's corresponding code snippets/samples/examples.

**Describe the solution you'd like**
A living/live design system with a URL, ah la React Storybook or other tool/service.
An example of this type of project can be found here — https://www.carbondesignsystem.com/

**Describe alternatives you've considered**
NA

**Additional context**
This will make UI design contributions and revisions easier and more efficient

**Comment by guylepage3** [comment]
We are planning on designing and building the design system tool for Meta. If you were to run the "Docs" for Meta you'll see the first iteration of this. Currently just a page showing the typography.

**Comment by guylepage3** [comment]
This has been started. The "Documentation" within Meta contains some all the editorial typography at the moment. Also "Meta UI Library" contains styles, componentry, etc.
