### ISSUE TITLE
Design a quick Meta logo

### ISSUE THREAD

**Issue by guylepage3** [universelabs/meta#43]
**Description**
Design a quick Meta logo

**Comment by aust-jacobite** [comment]
Hi, please can you provide more information about the logo let me help out?

**Comment by guylepage3** [comment]
Hey @aust-jacobite. Glad to see you're interested in helping out with the logo. I am about to push a v1 version of the logo, but would LOVE some help with a v2.

If you're still interested in helping out I can provide you with a very short creative brief. Let me know.

**Comment by guylepage3** [comment]
Meta logo set v1

<img width="1253" alt="screenshot 2019-01-16 07 37 00" src="https://user-images.githubusercontent.com/1711854/51249526-942cd900-1961-11e9-82c4-0819ef9c5eaf.png">

**Comment by guylepage3** [comment]
![meta-bug-512x512](https://user-images.githubusercontent.com/1711854/51249577-b45c9800-1961-11e9-8277-3d8a3d7b0f07.png)
![meta-bug-icon-rounded-512x512](https://user-images.githubusercontent.com/1711854/51249578-b45c9800-1961-11e9-9bcd-1e34c0b93fe4.png)
![meta-bug-icon-squared-512x512](https://user-images.githubusercontent.com/1711854/51249579-b45c9800-1961-11e9-9b15-78798820ed1f.png)
![meta-logo-wordmark-512x512](https://user-images.githubusercontent.com/1711854/51249580-b45c9800-1961-11e9-9c84-2b372bb7666d.png)

**Comment by guylepage3** [comment]
@aust-jacobite I'm closing this issue for now, but please do let me know if you'd like to take a stab at a v2 of the logo. 😄

**Comment by aust-jacobite** [comment]
Awesome @guylepage3,
Thanks for replying. 

Let me chew on the v2 set for you.
Please help me with the description so I can have a better idea and concept behind META.
