### ISSUE TITLE
*-editorial class modifier is missing from the Pattern Library

### ISSUE THREAD

**Issue by dantrevino** [universelabs/meta#55]
**Describe the bug**
*-editorial class modifier is missing from the Pattern Library.  As a developer I'm looking to the existing reference to be able to understand how classes will/should be applied.  The editorial modifier is not there.

**To Reproduce**
Run the Pattern Library.

**Expected behavior**
All classes/modifiers that are part of Meta should have documentation/reference in a single location.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Chrome
 - Version: 72

**Smartphone (please complete the following information):**
n/a

**Additional context**

**Comment by guylepage3** [comment]
Turns out `*-editorial` margins work correctly but the font sizes are not. Working on this issue now..

**Comment by guylepage3** [comment]
Ha. Everything is actually working correctly.. I just need to update the user instructions. I forgot that I changed how the `*-editorial` classes are used.

**Comment by guylepage3** [comment]
Updating the user instructions now..

**Comment by guylepage3** [comment]
Issue resolved. Updated instructions for `*-editorial` classes are here.. https://github.com/universelabs/meta/blob/master/DOCUMENTATION.md#editorial.
