### ISSUE TITLE
Make Pattern Library Available As A Web Page

### ISSUE THREAD

**Issue by dantrevino** [universelabs/meta#56]
**Is your feature request related to a problem? Please describe.**
Pattern Library reference currently requires a download/build/run cycle to view.  The examples/reference should be as easily available as possible.  See bootstrap typography:
https://getbootstrap.com/docs/4.0/content/typography/

**Describe the solution you'd like**
A web page, similar to bootstrap's typography page.

**Describe alternatives you've considered**
download/build/run cycle as currently required

**Additional context**
http://element.eleme.io/#/en-US/component/typography
https://vuetifyjs.com/en/framework/typography
https://bulma.io/documentation/modifiers/typography-helpers

**Comment by guylepage3** [comment]
This is being worked on here.. https://github.com/universelabs/meta/issues/26

**Comment by guylepage3** [comment]
Closing this issue and using the content above as a reference.
